### ISSUE TITLE
Livepeer logo to appear in DAO sidebar

### ISSUE THREAD

**Issue by chrishobcroft** [videoDAC/livepeer-delegator-aragon-app#3]
#### Current behaviour

Currently, the icon used for the Livepeer app seems to be a generic "file" icon (see screenshot below)

#### Expected behaviour

The icon for this should be the Livepeer icon - as per the image below.

Files also attached to this issue

![image](https://user-images.githubusercontent.com/2212651/55634760-066dc680-57b7-11e9-8959-587c31db1d2e.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/2212651/55634549-a414c600-57b6-11e9-8ba5-437c39850d45.png)

#### Files

![Livepeer_Mark_25px_Black](https://user-images.githubusercontent.com/2212651/55635056-b4797080-57b7-11e9-8fc5-0e1ebe36e5d2.png)
![Livepeer_Mark_200px_Black](https://user-images.githubusercontent.com/2212651/55635058-b4797080-57b7-11e9-9796-cc75652259c9.png)

**Comment by willjgriff** [comment]
Fixed as of commit: https://github.com/videoDAC/livepeer-delegator-aragon-app/commit/117a2371dee816d3c517d3f05a1576a877fa2ff9

**Comment by willjgriff** [comment]
Fixed as of commit: https://github.com/videoDAC/livepeer-delegator-aragon-app/commit/117a2371dee816d3c517d3f05a1576a877fa2ff9

**Comment by chrishobcroft** [comment]
Verified as fixed. Thank you
